import AppKit
import CryptoKit
import ImageIO
import UniformTypeIdentifiers

// Keep the transmitted PNG intact; provide TIFF only when a Mac app requests it.
// This avoids retaining an uncompressed copy of every received image in memory.
private final class PNGPasteboardProvider: NSObject, NSPasteboardItemDataProvider {
    private let png: Data
    init(_ png: Data) { self.png = png }
    func pasteboard(_ pasteboard: NSPasteboard?, item: NSPasteboardItem, provideDataForType type: NSPasteboard.PasteboardType) {
        guard type == .tiff else { return }
        autoreleasepool {
            guard let source = CGImageSourceCreateWithData(png as CFData, nil),
                  let image = CGImageSourceCreateImageAtIndex(source, 0, [kCGImageSourceShouldCache: false] as CFDictionary) else { return }
            let tiff = NSMutableData()
            guard let destination = CGImageDestinationCreateWithData(tiff, UTType.tiff.identifier as CFString, 1, nil) else { return }
            CGImageDestinationAddImage(destination, image, nil)
            if CGImageDestinationFinalize(destination) { item.setData(tiff as Data, forType: .tiff) }
        }
    }
}

private final class ImageFilePasteboardProvider: NSObject, NSPasteboardItemDataProvider {
    let url: URL
    private var png: Data?
    init(_ url: URL) { self.url = url }
    func pasteboard(_ pasteboard: NSPasteboard?, item: NSPasteboardItem, provideDataForType type: NSPasteboard.PasteboardType) {
        autoreleasepool {
            if png == nil {
                guard let size = try? FileIdentity.at(url).size, size <= 64 * 1024 * 1024,
                      let data = try? Data(contentsOf: url, options: .mappedIfSafe) else { return }
                png = ClipBoard.normalizedPNG(data)
            }
            guard let png else { return }
            if type == .png { item.setData(png, forType: .png) }
            else if type == .tiff { PNGPasteboardProvider(png).pasteboard(pasteboard, item: item, provideDataForType: type) }
        }
    }
}

final class ClipBoard {
    private let board: NSPasteboard
    private var timer: Timer?
    private var lastChange = 0
    var onChange: (Packet) -> Void = { _ in }
    var onLocalChange: () -> Void = {}
    var onFiles: (([URL]) -> Void)?
    var onLargeText: ((String) -> Void)?
    var onStatus: (String) -> Void = { _ in }
    var changeVersion: Int { board.changeCount }
    init(board: NSPasteboard = .general) { self.board = board }
    func start() {
        stop()
        lastChange = board.changeCount
        let timer = Timer(timeInterval: 0.75, repeats: true) { [weak self] _ in self?.check() }
        timer.tolerance = 0.15
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }
    func stop() { timer?.invalidate(); timer = nil }
    private func check() {
        guard board.changeCount != lastChange else { return }
        capture()
    }
    func capture() {
        lastChange = board.changeCount
        onLocalChange()
        let types = Set(board.types ?? [])
        let excluded = ["org.nspasteboard.TransientType", "org.nspasteboard.ConcealedType", "org.nspasteboard.AutoGeneratedType", "application/x-keepassxc-private", "com.agilebits.onepassword"]
        guard !excluded.contains(where: { types.contains(NSPasteboard.PasteboardType($0)) }) else { return }
        autoreleasepool {
            var packet: Packet?
            if types.contains(.fileURL) {
                if let onFiles {
                    guard let urls = board.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
                          (1...32).contains(urls.count), board.changeCount == lastChange else { onStatus("一次最多复制 32 个普通文件"); return }
                    onFiles(urls); return
                }
                guard let urls = board.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
                      urls.count == 1, let url = urls.first, url.isFileURL,
                      ["png", "jpg", "jpeg"].contains(url.pathExtension.lowercased()) else {
                    onStatus("仅支持复制单张 PNG/JPG 图片文件"); return
                }
                do {
                    let info = try url.resourceValues(forKeys: [.isRegularFileKey, .fileSizeKey])
                    guard info.isRegularFile == true, let size = info.fileSize, size > 0, size <= 64 * 1024 * 1024 else {
                        onStatus("图片文件过大或不可读取，已跳过"); return
                    }
                    let file = try FileHandle(forReadingFrom: url)
                    defer { try? file.close() }
                    guard let data = try file.read(upToCount: 64 * 1024 * 1024 + 1), data.count <= 64 * 1024 * 1024,
                          let source = CGImageSourceCreateWithData(data as CFData, nil),
                          let type = CGImageSourceGetType(source),
                          [UTType.png.identifier, UTType.jpeg.identifier].contains(type as String),
                          let png = Self.normalizedPNG(data) else {
                        onStatus("图片格式无效或超过 8 MiB / 1600 万像素，已跳过"); return
                    }
                    packet = Packet(kind: 2, body: png)
                } catch { onStatus("无法读取这张图片文件，已跳过"); return }
            } else if types.contains(.png), let data = board.data(forType: .png) {
                guard Wire.pngValid(data) else { onStatus("图片太大或格式无效，已跳过"); return }
                packet = Packet(kind: 2, body: data)
            } else if types.contains(.tiff), let data = board.data(forType: .tiff) {
                guard let png = Self.normalizedPNG(data) else { onStatus("图片格式无效或超过 8 MiB / 1600 万像素，已跳过"); return }
                packet = Packet(kind: 2, body: png)
            } else if let text = board.string(forType: .string) {
                let count = text.utf8.count
                guard count <= StreamWire.maxText else { onStatus("文字超过 10 MiB，已跳过"); return }
                if count > Wire.maxText, let onLargeText {
                    guard board.changeCount == lastChange else { return }; onLargeText(text); return
                }
                let data = Data(text.utf8)
                guard data.count <= Wire.maxText else { onStatus("文字超过 1 MiB，已跳过"); return }
                packet = Packet(kind: 1, body: data)
            }
            // A producer can update the clipboard while rendering delayed formats.
            guard board.changeCount == lastChange, let packet else { return }
            onChange(packet)
        }
    }
    static func normalizedPNG(_ data: Data) -> Data? {
        guard data.count <= 64 * 1024 * 1024,
              let source = CGImageSourceCreateWithData(data as CFData, nil),
              let info = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let w = info[kCGImagePropertyPixelWidth] as? Int,
              let h = info[kCGImagePropertyPixelHeight] as? Int,
              w > 0, h > 0, w <= 16_000_000, h <= 16_000_000, w * h <= 16_000_000,
              let image = CGImageSourceCreateImageAtIndex(source, 0, [kCGImageSourceShouldCache: false] as CFDictionary) else { return nil }
        if CGImageSourceGetType(source).map({ $0 as String }) == UTType.png.identifier, Wire.pngValid(data) { return data }
        let png = NSMutableData()
        guard let dest = CGImageDestinationCreateWithData(png, UTType.png.identifier as CFString, 1, nil) else { return nil }
        CGImageDestinationAddImage(dest, image, nil)
        guard CGImageDestinationFinalize(dest), Wire.pngValid(png as Data) else { return nil }
        return png as Data
    }
    func apply(_ packet: Packet) throws {
        if packet.kind == 0 { return }
        try Wire.validate(packet)
        let item = NSPasteboardItem()
        if packet.kind == 1 {
            guard let text = String(data: packet.body, encoding: .utf8), item.setString(text, forType: .string) else { throw ClipError.invalid }
        } else if packet.kind == 2 {
            // Decode before clearing the clipboard so corrupt PNG cannot destroy it.
            guard let source = CGImageSourceCreateWithData(packet.body as CFData, nil),
                  CGImageSourceCreateImageAtIndex(source, 0, [kCGImageSourceShouldCache: false] as CFDictionary) != nil,
                  item.setData(packet.body, forType: .png),
                  item.setDataProvider(PNGPasteboardProvider(packet.body), forTypes: [.tiff]) else { throw ClipError.invalid }
        } else { throw ClipError.invalid }
        board.clearContents()
        guard board.writeObjects([item]) else { throw ClipError.invalid }
        lastChange = board.changeCount
    }
    func apply(_ received: ReceivedStream, expectedVersion: Int) throws {
        guard board.changeCount == expectedVersion, !received.urls.isEmpty else { throw ClipError.replay }
        var items: [NSPasteboardItem] = []
        if received.offer.type == "text" {
            let item = NSPasteboardItem()
            guard try FileIdentity.at(received.urls[0]).size <= UInt64(StreamWire.maxText),
                  let text = String(data: try Data(contentsOf: received.urls[0], options: .mappedIfSafe), encoding: .utf8),
                  item.setString(text, forType: .string) else { throw ClipError.invalid }
            items = [item]
        } else {
            for url in received.urls {
                let item = NSPasteboardItem(), writer = url as NSURL
                for type in writer.writableTypes(for: board) {
                    if let value = writer.pasteboardPropertyList(forType: type) {
                        if let string = value as? String { item.setString(string, forType: type) }
                        else if let data = value as? Data { item.setData(data, forType: type) }
                        else { item.setPropertyList(value, forType: type) }
                    }
                }
                items.append(item)
            }
            if received.urls.count == 1, ["png", "jpg", "jpeg"].contains(received.urls[0].pathExtension.lowercased()) {
                items[0].setDataProvider(ImageFilePasteboardProvider(received.urls[0]), forTypes: [.png, .tiff])
            }
        }
        guard board.changeCount == expectedVersion else { throw ClipError.replay }
        board.clearContents()
        guard board.writeObjects(items) else { throw ClipError.invalid }
        lastChange = board.changeCount
    }
}
